# https://taskfile.dev

version: "3"

set: [errexit, nounset, pipefail, xtrace]

dotenv: [".env"]

tasks:
  repl:
    cmds:
      - uv run python3
  ruff_check:
    cmds:
      - uv run ruff check
      - uv run ruff format --check
  ruff_fix:
    cmds:
      - uv run ruff check --fix 
      - uv run ruff format
  pyright_check:
    cmds:
      - uv run pyright
  app_env:
    cmds:
      - uv run main.py
  build_app:
      - docker build . -t family_finance
  run_app_dev:
    cmds:
      - docker-compose -f docker-compose.yaml -f docker-compose-dev.yaml up
  run_app:
    cmds:
      - docker-compose -f docker-compose.yaml up -d
  run_app_manually:
    cmds:
      - uv run fastapi dev app/main.py --port 80 --host 0.0.0.0
  init_ngrok:
    cmds:
      - ngrok http 80
